"""Report generator: TXT, JSON, HTML."""

import json
import os
from datetime import datetime
from typing import Any, Dict

HTML_CSS = """
body { font-family: 'Segoe UI', Arial, sans-serif; background: #0d1117; color: #c9d1d9; margin: 0; padding: 20px; }
h1 { color: #58a6ff; border-bottom: 2px solid #58a6ff; padding-bottom: 8px; }
h2 { color: #79c0ff; margin-top: 30px; }
h3 { color: #ffa657; }
.card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; margin: 12px 0; }
.kv { display: grid; grid-template-columns: 200px 1fr; gap: 6px 12px; }
.k { color: #8b949e; }
.v { color: #c9d1d9; word-break: break-word; }
.tag { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 12px; margin: 2px; }
.tag-ok { background: #1f6f37; color: #fff; }
.tag-warn { background: #9e6a03; color: #fff; }
.tag-err { background: #b62324; color: #fff; }
.tag-info { background: #1f6feb; color: #fff; }
pre { background: #010409; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 12px; }
a { color: #58a6ff; }
.footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #30363d; color: #6e7681; font-size: 12px; }
"""


def _json_default(o: Any) -> str:
    try:
        return str(o)
    except Exception:
        return ""


def to_json(data: Dict[str, Any]) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False, default=_json_default)


def to_txt(data: Dict[str, Any], title: str = "OSINT Report") -> str:
    lines = [
        "=" * 70,
        f"  {title}",
        f"  Generated: {datetime.now().isoformat()}",
        "=" * 70,
        "",
    ]

    def _walk(obj, depth=0):
        pad = "  " * depth
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, (dict, list)):
                    lines.append(f"{pad}{k}:")
                    _walk(v, depth + 1)
                else:
                    lines.append(f"{pad}{k}: {v}")
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                if isinstance(v, (dict, list)):
                    lines.append(f"{pad}[{i}]:")
                    _walk(v, depth + 1)
                else:
                    lines.append(f"{pad}[{i}] {v}")
        else:
            lines.append(f"{pad}{obj}")

    _walk(data)
    lines.append("")
    lines.append("=" * 70)
    lines.append("Generated by OCySec OSINT Framework")
    return "\n".join(lines)


def _render_value(v: Any) -> str:
    if v is None:
        return '<span class="v">-</span>'
    if isinstance(v, bool):
        cls = "tag-ok" if v else "tag-err"
        text = "TRUE" if v else "FALSE"
        return f'<span class="tag {cls}">{text}</span>'
    if isinstance(v, (int, float)):
        return f'<span class="v">{v}</span>'
    s = str(v)
    if len(s) > 200:
        s = s[:200] + "..."
    if s.startswith("http"):
        return f'<a href="{s}" target="_blank" rel="noopener">{s}</a>'
    return f'<span class="v">{s}</span>'


def _render_kv(d: Dict[str, Any]) -> str:
    rows = []
    for k, v in d.items():
        if isinstance(v, (dict, list)):
            continue
        rows.append(f'<div class="k">{k}</div><div class="v">{_render_value(v)}</div>')
    return f'<div class="kv">{"".join(rows)}</div>'


def _render_nested(obj: Any, depth: int = 0) -> str:
    if isinstance(obj, dict):
        if all(not isinstance(v, (dict, list)) for v in obj.values()):
            return _render_kv(obj)
        parts = []
        for k, v in obj.items():
            parts.append(f"<h3>{k}</h3>")
            parts.append(f'<div class="card">{_render_nested(v, depth + 1)}</div>')
        return "".join(parts)
    if isinstance(obj, list):
        if not obj:
            return "<p><em>(empty)</em></p>"
        if all(isinstance(x, (str, int, float, bool)) for x in obj):
            return ", ".join(str(x) for x in obj)
        parts = []
        for i, item in enumerate(obj):
            parts.append(
                f'<div class="card"><h3>Item {i + 1}</h3>{_render_nested(item, depth + 1)}</div>'
            )
        return "".join(parts)
    return f"<p>{_render_value(obj)}</p>"


def to_html(data: Dict[str, Any], title: str = "OSINT Report") -> str:
    body = _render_nested(data)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>{HTML_CSS}</style>
</head>
<body>
<h1>{title}</h1>
<p class="k">Generated: {datetime.now().isoformat()} | Framework: OCySec OSINT v2.0</p>
{body}
<div class="footer">
    OCySec OSINT Framework - Authorized Penetration Testing Only.
    Selalu dapatkan izin tertulis sebelum melakukan OSINT pada target.
</div>
</body>
</html>
"""


def save_report(
    out_dir: str, target: str, data: Dict[str, Any], formats: list = None
) -> Dict[str, str]:
    """Simpan laporan dalam beberapa format. Return dict {format: path}."""
    if formats is None:
        formats = ["txt", "json", "html"]
    os.makedirs(out_dir, exist_ok=True)
    safe_target = "".join(c if c.isalnum() or c in "._-" else "_" for c in target)[:64] or "target"
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    written: Dict[str, str] = {}
    base = f"{safe_target}_{ts}"
    if "json" in formats:
        p = os.path.join(out_dir, f"{base}.json")
        with open(p, "w", encoding="utf-8") as f:
            f.write(to_json(data))
        written["json"] = p
    if "txt" in formats:
        p = os.path.join(out_dir, f"{base}.txt")
        with open(p, "w", encoding="utf-8") as f:
            f.write(to_txt(data, f"OSINT Report - {target}"))
        written["txt"] = p
    if "html" in formats:
        p = os.path.join(out_dir, f"{base}.html")
        with open(p, "w", encoding="utf-8") as f:
            f.write(to_html(data, f"OSINT Report - {target}"))
        written["html"] = p
    return written
